In [66]:
import numpy as np 
a = np.array([1, 2, 3, 4])
print (a)

[1 2 3 4]


In [8]:
# importing the time fucntion for clock time of the computer
import time

# generating two vectors of million dimension
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# to register the clock time when operation starts
tic = time.time()

# Calculating the Cost function (a-transpose * b). This is the vectorized version calculation 
# of Cost Function
c = np.dot(a,b)

# registering the clock time at the end of calculation
toc = time.time()

# Finding how much time it took to calculate
print ("vectorized version:" + str(1000*(toc-tic)) + "ms")
print(c)

vectorized version:1.0030269622802734ms
249837.161868


In [12]:
d = 0
tic = time.time()

# Cost Function calculation using the 'for' loop
for i in range(1000000):
    d += a[i]*b[i]

toc = time.time()

print ("for loop calculation:" + str(1000*(toc-tic)) + "ms")
print(d)
print(c)
    

for loop calculation:588.2000923156738ms
249837.161868
249837.161868


In [7]:
import numpy as np
A = np.array([[56, 0.0, 4.0, 68.0],
            [1.2, 104, 52, 8.0],
            [1.8, 135, 99, 0.9]])
print (A)

[[  56.     0.     4.    68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [9]:
cal = A.sum(axis=0)
print (cal)

[  59.   239.   155.    76.9]


In [11]:
percentage = 100*A/cal.reshape(1,4)
print (percentage)

[[ 94.91525424   0.           2.58064516  88.42652796]
 [  2.03389831  43.51464435  33.5483871   10.40312094]
 [  3.05084746  56.48535565  63.87096774   1.17035111]]


In [12]:
a = np.random.randn(5)

In [13]:
print(a)

[-1.14131223 -0.66784918 -0.53402635 -1.10164544 -0.3278256 ]


In [14]:
print(a.shape)

(5,)


In [15]:
print(a.T)

[-1.14131223 -0.66784918 -0.53402635 -1.10164544 -0.3278256 ]


In [16]:
b = np.random.randn(5,1)

In [17]:
print(b)

[[ 1.72749558]
 [-1.57460868]
 [ 1.29387766]
 [-0.78676044]
 [ 1.39589487]]


In [21]:
print(b.shape)

(5, 1)


In [18]:
print(b.T)

[[ 1.72749558 -1.57460868  1.29387766 -0.78676044  1.39589487]]


In [19]:
print(np.dot(a, a.T))

3.35489256779


In [20]:
print(np.dot(b, b.T))

[[ 2.98424098 -2.72012953  2.23516795 -1.35912518  2.41140223]
 [-2.72012953  2.47939248 -2.03735099  1.23883981 -2.19798818]
 [ 2.23516795 -2.03735099  1.67411941 -1.01797176  1.8061172 ]
 [-1.35912518  1.23883981 -1.01797176  0.61899199 -1.09823486]
 [ 2.41140223 -2.19798818  1.8061172  -1.09823486  1.9485225 ]]


In [28]:
a1 = a.reshape(1, 5)

In [29]:
print(a1)

[[-1.14131223 -0.66784918 -0.53402635 -1.10164544 -0.3278256 ]]


In [30]:
print(a1.shape)

(1, 5)


In [31]:
print(a1.T)

[[-1.14131223]
 [-0.66784918]
 [-0.53402635]
 [-1.10164544]
 [-0.3278256 ]]


In [33]:
print(np.dot(a1.T, a1))

[[ 1.3025936   0.76222444  0.6094908   1.25732141  0.37415136]
 [ 0.76222444  0.44602253  0.35664906  0.735733    0.21893805]
 [ 0.6094908   0.35664906  0.28518414  0.58830769  0.17506751]
 [ 1.25732141  0.735733    0.58830769  1.21362268  0.36114757]
 [ 0.37415136  0.21893805  0.17506751  0.36114757  0.10746962]]


In [36]:
c = np.random.randn(3, 3)
d = np.random.randn(3, 1)
p = c*d
print(p)

[[-1.58688687  3.16962443  2.96087074]
 [ 0.44513307  0.12750419  0.63191242]
 [-2.87305462 -1.84201051 -0.11862372]]


In [37]:
print(p.shape)

(3, 3)


In [38]:
e = np.random.randn(12288, 150)
f = np.random.randn(150, 45)
g = np.dot(e,f)

In [40]:
print(g.shape)

(12288, 45)


In [56]:
h = np.random.randn(3, 4)
i = np.random.randn(4, 1)

In [57]:
print(h.shape)
print(i.shape)

(3, 4)
(4, 1)


In [71]:
j = i + h
print(j)

ValueError: operands could not be broadcast together with shapes (4,1) (3,4) 

In [51]:
print(j.shape)

(2, 3)


In [72]:
k = h + i.T
print(k)

[[ 0.8687137   1.07265867 -0.47372001 -1.51370146]
 [-0.212576   -0.69476058  3.1383132  -1.45023605]
 [ 0.17820405 -0.96763342  1.56959344 -0.12425901]]
